[build]
  command = "npm run build"
  publish = "build"
  
[[redirects]]
    from = "/*"                   # Redirect all requests
    to = "/index.html"            # Serve the React app for all routes
    status = 200   
